### ISSUE TITLE
Deleting a list should delete the tasks

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-training-todo#103]
Right now the behavior is:
- Deleting a list does not delete tasks
- If the list is recreated with new tasks all the old tasks are shown as well. 

Ideal behavior:
- A recreated list should be blank due to the deletion of the original list

**Comment by borrrden** [comment]
Has this been observed?  The new list should have a different ID if it is generated by the application.  However, it is probably a good idea to clean up things that are not being used anymore.
