### ISSUE TITLE
Crash in Xamarin Android todo when creating a list.

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-training-todo#111]
Using Todo - fc3bdc4b4a4901c3f5368d37379ecf1d06b79351
Using .NET SQLCipher, Xamarin Android (1.4.-37), Nexus 5 device with Android 6.0.1

- Sign In
- Create a list
- CRASH!

I had the debugger attached from Xamarin Studio which I think may have cause it. Have you seen this happen @borrrden? 

I used the app without the debugger for the rest of the test session with no issues.

**Comment by borrrden** [comment]
I've seen the android debugger cause crashing for no reason many times so I
wouldn't rule it out. This is especially the case if there is no exception
or anything.

**Comment by sethrosetter** [comment]
I'm 99% that is what happened. I created many lists after that with no issue. Let keep it open to test during next test fest. If it doesn't crash, lets close it.

**Comment by jamiltz** [comment]
@sethrosetter can we close this?

**Comment by sethrosetter** [comment]
I believe it was debugger related. Lets close and reopen if we see it again.
