### ISSUE TITLE
(Xamarin iOS) Image rotated when taking picture with camera

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-training-todo#114]
Xamarin iOS - iPhone 5, iOS 8, CBL ver. 1.4-37

- Create list
- Create task
- Update task with image from camera

Expected
- image is added with the correct orientation
- when shared image syncs and shows up in the correct orientation

Actual
- image is rotated 90 degrees
- It showed in the correct orientation when sync'ing with with iOS 10.2 device

**Comment by borrrden** [comment]
I'm almost sure this has to do with EXIF data nonsense.  It's probably beyond the scope of this application to try to fix it.
