### ISSUE TITLE
Android ToDo app does not have storage permissions

### ISSUE THREAD

**Issue by raghusarangapani** [couchbaselabs/mobile-training-todo#115]
Steps:
- Check out the latest todo
- Build and install the app from android studio
- Create a list and add some tasks to the list
- Choose a photo for one of the lists from the device's existing photo gallery.

Expected:
- Picture should get assigned to the task 

Actual:
- ToDo app crashes

Crash stack trace:
 https://gist.github.com/raghusarangapani/6dafcf20acd065c2eb9cb66fef3a6f7c

Workaround:
Manually grant storage permissions to the ToDo app.

**Comment by jamiltz** [comment]
Not sure how to reproduce, wasn't able to perform step 4 on the emulator:

> - Choose a photo for one of the lists from the device's existing photo gallery.

Image picking isn't working on the nexus 5 emulator on my setup #120
