### ISSUE TITLE
[React-Native] Not working on android

### ISSUE THREAD

**Issue by tienlm1509** [couchbaselabs/mobile-training-todo#125]
Error component: 
![d308bcce0daf4cdeb1b6efcf0d20a4f5](https://cloud.githubusercontent.com/assets/9527460/24999963/bece1c34-2069-11e7-84ee-1140f3919def.png)
Replicate not working: 
 step 1: add list
![d7ba4c8fc9e9499bb8e41a3700d9721a](https://cloud.githubusercontent.com/assets/9527460/24999976/c849c59c-2069-11e7-9269-8f6de6057a37.png)
 step 2: sync gateway do nothing
![beee333a5fa646109b514437ffa3abd7](https://cloud.githubusercontent.com/assets/9527460/24999984/cd91c4aa-2069-11e7-91bc-43b5cda764de.png)

**Comment by jamiltz** [comment]
When does the error on the first screenshot appear?

**Comment by jamiltz** [comment]
Regarding the replication not working, it could be because the Android emulator is running in its own VM. The README was updated with the instructions to get around this.

Without logs it's hard to tell why the documents are not replicated to SG but this could be a reason.

**Comment by tienlm1509** [comment]
thank you !
