### ISSUE TITLE
Add XAttrs Sync Gateway Config File to the tutorial repo

### ISSUE THREAD

**Issue by ssmotra** [couchbaselabs/mobile-training-todo#130]
Add a new Sync Gateway Config to the tutorial repo to include the following 

- Enable extended attribute support
 "to-do": {
            "import_docs": "continuous",
            "unsupported": {
                "enable_extended_attributes": true
            },

- Add version compatibility note in the config file - Need Couchbase Server 5.0 or newer and Sync Gateway 1.5 or newer

**Comment by sethrosetter** [comment]
Can't comment in json. The readme should be updated.

**Comment by sethrosetter** [comment]
closed via - https://github.com/couchbaselabs/mobile-training-todo/pull/128
