### ISSUE TITLE
Replication in api-v2

### ISSUE THREAD

**Issue by mr-jingles** [couchbaselabs/mobile-training-todo#140]
Is the replication via sync-gateway supposed to work with couchbase lite db010 and sync gateway 1.5.0-377? When I run the WPF Demo - I can add todo-list and tasks, but no documents get replicated to sync-gateway. Hint and replication uri are set.

**Comment by mr-jingles** [comment]
Found this in the Log-Files

`[INFO] DB (DB) [1] 2017-6-26 06:04:35.520+02:00 Opening DataFile
[INFO] LITECORE (BLIP) [1] 2017-6-26 06:04:35.531+02:00 {1}--> ->blip:10.0.2.2:4984/db/_blipsync
[INFO] LITECORE (BLIP) [1] 2017-6-26 06:04:35.531+02:00 {1} Opening connection...
[INFO] LITECORE (Actor) [1] 2017-6-26 06:04:35.533+02:00 Starting Scheduler<084190F0> with 1 threads
[INFO] LITECORE (Actor) [7] 2017-6-26 06:04:35.539+02:00 BLIP[->blip:10.0.2.2:4984/db/_blipsync] performNextMessage
[...]
[INFO] SYNC (Replicator) [8] 2017-6-26 06:04:35.625+02:00 Replicator[<*> blip://10.0.2.2:4984/db/] is Connecting, progress 0/0
WARN TASK SCHEDULING (SerialQueue) [9] 2017-6-26 06:04:36.498+02:00 Exception during DispatchAsync:
System.ArgumentException: Keine der ermittelten oder angegebenen Adressen entspricht der Socketadressfamilie.
Parametername: context
   bei System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
   bei System.Net.Sockets.Socket.DoDnsCallback(IAsyncResult result, MultipleAddressConnectAsyncResult context)
   bei System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   bei System.Net.Sockets.TcpClient.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   bei System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   bei System.Net.Sockets.TcpClient.ConnectAsync(String host, Int32 port)
   bei Couchbase.Lite.Sync.WebSocketWrapper.<Start>b__25_0()
   bei Couchbase.Lite.Support.SerialQueue.ProcessAsync()`

**Comment by mr-jingles** [comment]
Found this: https://github.com/couchbase/couchbase-lite-net/issues/880

I am not sure how to close this issue.

**Comment by jamiltz** [comment]
Is it working now then?

**Comment by mr-jingles** [comment]
I am waiting for db011 to be released on http://mobile.nuget.couchbase.com/nuget/Developer/ and will test it again. But I guess this issue is very likely a duplicate of the one reported on the couchbase-lite-net project.

**Comment by jamiltz** [comment]
Ok, I'll close this ticket and you can reopen if it happens again with db11.
