### ISSUE TITLE
2.0: Android - CouchBaseLite 2.0 Replication Error When multiple clients delete Documents

### ISSUE THREAD

**Issue by loongsun** [couchbaselabs/mobile-training-todo#144]
now ,I using ToDo Example(Couchbase lite 2.0 beta 011) to test Replication Items。i runing app on the multiple android devices, I found add\update items replication is okey.but when one client delete a document,the other client document does not change anything.i don't know what happened.

**Comment by hideki** [comment]
REF: https://github.com/couchbase/couchbase-lite-android/issues/1242

**Comment by hideki** [comment]
REF: https://forums.couchbase.com/t/couchbaselite-2-0-replication-error-when-multiple-clients-delete-documents/13341

**Comment by hideki** [comment]
As this issue has been tracked with couchbase-lite-android repository, I will close this.
