### ISSUE TITLE
V2.0 Windows: Crash at login

### ISSUE THREAD

**Issue by mohsens22** [couchbaselabs/mobile-training-todo#145]
I'm trying to work with ToDo sample in V2.0 and I see that it crashes in login :| 
My couchbase server 5.0 and sync gateway 1.5 is configured.
Installed couchbase server and did initial configuration. Then installed sync 1.5 and ran with that config file.
![image](https://user-images.githubusercontent.com/22152065/27991496-1da3b3fa-648e-11e7-979f-2079c7312b7c.png)
I face this in UWP and WPF

**Comment by borrrden** [comment]
Is this still the case?

**Comment by borrrden** [comment]
P.S. FYI Use the feature/2.0 branch now instead of api-v2

**Comment by pasin** [comment]
Please reopen if the issue still exists in branch feature/2.0.
