### ISSUE TITLE
2.0: Android - Do I need to setup new configurations for my couch sync gateway ?

### ISSUE THREAD

**Issue by amansinghal** [couchbaselabs/mobile-training-todo#147]
**Hi All,**
**I am getting following error logs while starting replication :**

com.couchbase.todo I/InstantRun: starting instant run server: is main process
com.couchbase.todo I/LiteCore [DB]: Opening DataFile
com.couchbase.todo I/Sync: Replicator[<* http://10.10.100.43:4984/test/]: Starting
com.couchbase.todo I/LiteCoreJNI: [NATIVE] C4Replicator.create()
com.couchbase.todo I/LiteCore [DB]: Opening DataFile
com.couchbase.todo I/LiteCore [DB]: Closing DataFile
com.couchbase.todo E/Sync: Replicator[<* http://10.10.100.43:4984/test/] is stopped, progress 0/0, error: CouchbaseLiteException{domain=1, code=15}
com.couchbase.todo I/Sync: C4ReplicatorListener.statusChanged() status -> C4ReplicatorStatus{activityLevel=0, progressCompleted=0, progressTotal=0, errorDomain=1, errorCode=15, errorInternalInfo=0}
com.couchbase.todo W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
com.couchbase.todo I/Query: com.couchbase.lite.LiveQuery@7e8de05: Querying...
com.couchbase.todo I/LiteCore [SQL]: Compiled Query: SELECT sequence, key, version, flags FROM kv_default WHERE fl_value(body, 'type') = 'task-list' ORDER BY fl_value(body, 'name')
com.couchbase.todo I/LiteCore [SQL]: Created prerecorded query enum with 0 rows (2 bytes) in 0.016ms
com.couchbase.todo D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
                                     
                                     [ 07-14 02:06:11.049 19252:19252 D/         ]
                                     HostConnection::get() New Host Connection established 0xeb0e2ab0, tid 19252
com.couchbase.todo E/Sync: statusChanged() c4Status -> C4ReplicatorStatus{activityLevel=0, progressCompleted=0, progressTotal=0, errorDomain=1, errorCode=15, errorInternalInfo=0}
com.couchbase.todo E/Sync: Replicator[<* http://10.10.100.43:4984/test/] is stopped, progress 0/0, error: CouchbaseLiteException{domain=1, code=15}
com.couchbase.todo I/Application: [Todo] Replicator: status -> STOPPED, error -> CouchbaseLiteException{domain=1, code=15}
com.couchbase.todo W/System.err: CouchbaseLiteException{domain=1, code=15}
com.couchbase.todo W/System.err:     at com.couchbase.lite.Replicator.updateStateProperties(Replicator.java:532)
com.couchbase.todo W/System.err:     at com.couchbase.lite.Replicator.c4StatusChanged(Replicator.java:473)
com.couchbase.todo W/System.err:     at com.couchbase.lite.Replicator.access$000(Replicator.java:37)
com.couchbase.todo W/System.err:     at com.couchbase.lite.Replicator$1$1.run(Replicator.java:374)
com.couchbase.todo W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
com.couchbase.todo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
com.couchbase.todo W/System.err:     at android.os.Looper.loop(Looper.java:148)
com.couchbase.todo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
com.couchbase.todo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
com.couchbase.todo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
com.couchbase.todo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
com.couchbase.todo D/libEGL: loaded /system/lib/egl/libEGL_emulation.so
com.couchbase.todo D/libEGL: loaded /system/lib/egl/libGLESv1_CM_emulation.so
com.couchbase.todo D/libEGL: loaded /system/lib/egl/libGLESv2_emulation.so
                             
                             [ 07-14 02:06:11.315 19252:19315 D/         ]
                             HostConnection::get() New Host Connection established 0xeea12af0, tid 19315
com.couchbase.todo I/OpenGLRenderer: Initialized EGL, version 1.4
com.couchbase.todo W/EGL_emulation: eglSurfaceAttrib not implemented

**I am using sync gateway which I was using for couch base lite 1.4.0.**

**Kindly address me Do I need to update my sync gateway also to use couchbase lite 2.0 feature.**

**Comment by hideki** [comment]
To use CBL v2.x, it requires latest sync gateway build. you could download from http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.5.0/

And also the special configuration in Sync Gateway configuration file. Need to add following:
```json
      "unsupported": {
        "replicator_2":true
      }
```
Please refere sync gateway confiuration file example in 
 https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/native-api/replication/index.html
