### ISSUE TITLE
CouchBase Lite 2.0 , Document's Blob Data  can't replicate to another client???

### ISSUE THREAD

**Issue by loongsun** [couchbaselabs/mobile-training-todo#150]
I find Document's blob data dos't replicate to another client in my app (DB012),and i test the todo example,this question happens also!

**Comment by borrrden** [comment]
Which platform?  DB012 has three different versions

**Comment by loongsun** [comment]
android

**Comment by hideki** [comment]
Hi @loongsun,

This is a known issue. We will fix this as soon as possible.
https://github.com/couchbase/sync_gateway/issues/2611

**Comment by hideki** [comment]
This issue is no longer reproducible with
- SG 1.5.0-555
- CBL Android DB016
