### ISSUE TITLE
2.0: Android - DB014 delete data report errors

### ISSUE THREAD

**Issue by zhuangpeng** [couchbaselabs/mobile-training-todo#153]
hello:
    thank you for release couchbase lite(db14)  todo lite demo.
    I installed on two android pad.when I delete a item, the another pad not sync. and android studio console prompt errors:
Environment：couchbase 5.0 beta 2
sync-gateway: 1.5 - 447
couchbase lite: db13
![image](https://user-images.githubusercontent.com/14283213/29024201-89307ac8-7ba3-11e7-8cd3-90a343b420e5.png)

**Comment by rajagp** [comment]
@hideki  Is this issue related to https://github.com/couchbase/couchbase-lite-android/issues/1242. That ticket appears to have been fixed though (on lite core).

**Comment by hideki** [comment]
Hi  @zhuangpeng and @rajagp,

I believe this issue is addressed. I did not confirm it with ToDo sample. But I don't have time to verify right now. This fix requires latest Sync Gateway build. I assume the build on the download page is outdated.

Could you please test this with latest SG build? If the issue is still reproducible, please reopen the ticket?  couchbase/couchbase-lite-android#1242
http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.5.0/1.5.0-515/

**Comment by zhuangpeng** [comment]
Hi @hideki @rajagp ,
    thanks for your reply. I updated sync_gateway to 1.5.0-151,when I delete data, the android studio console log still report above error. I guess maybe my code issue, can you give me a delete data sample code?  below is todo list delete data code segment.
![image](https://user-images.githubusercontent.com/14283213/29054683-2a475d60-7c2a-11e7-8d9f-8bd9d31d8648.png)
![image](https://user-images.githubusercontent.com/14283213/29054685-2e940e54-7c2a-11e7-93f5-264417f4c4df.png)
![image](https://user-images.githubusercontent.com/14283213/29054688-351a0e5e-7c2a-11e7-943e-ab372486c1ae.png)

**Comment by hideki** [comment]
With `feature/2.0` branch of couchbase-lite-android commit 468e98cc523096ce60f8623f9c9d4d3997827767 .

There are two deleted document replication problems.
1. push replicator does not replicate the deleted document.
2. After pull replicated the deleted document, Live Query returns the empty result for the deleted document.

**Comment by hideki** [comment]
1. Push replication issue with the deleted document -> Ticket: 
 https://github.com/couchbase/couchbase-lite-core/issues/263

2. ToDo's ListView or LiveQuery issue with pull replicated deleted document -> Ticket:
https://github.com/couchbaselabs/mobile-training-todo/issues/161

**Comment by hideki** [comment]
With [LiteCore module's fix](https://github.com/couchbase/couchbase-lite-core/commit/962c4021e431394d068a1b4582edf6565d3be145), this issue is fixed.
