### ISSUE TITLE
when will release the db17 version?

### ISSUE THREAD

**Issue by zhuangpeng** [couchbaselabs/mobile-training-todo#162]
thanks!

**Comment by loongsun** [comment]
The waiting time is too long！

**Comment by rajagp** [comment]
We are coming out with another update - DB18 will be released shortly (in a week or so). The todo sample app corresponding to DB18 will be released soon after 
(CC @hideki , @pasin , @djpongh ? )

**Comment by djpongh** [comment]
DB18  is out and the docs/sample app have been updated.
