### ISSUE TITLE
Update Docment,but liveQuery not change!

### ISSUE THREAD

**Issue by loongsun** [couchbaselabs/mobile-training-todo#164]
In DB019, when  i update a Document,but LiveQuery not change, not changelishen anything!

**Comment by loongsun** [comment]
I test with your todo example in the android studio.

**Comment by pasin** [comment]
I believe this is fixed by https://github.com/couchbaselabs/mobile-training-todo/commit/1c5b6b47a451331bbf7762bdac3a40339745cc1a
