### ISSUE TITLE
CBL 2.0 DB021 not available

### ISSUE THREAD

**Issue by jdulaney** [couchbaselabs/mobile-training-todo#169]
Have been using DB020 no problem, but gradle is unable to resolve DB021

Error:Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.couchbase.lite:couchbase-lite-android:2.0.0-DB021.

**Comment by hideki** [comment]
Hi @jdulaney,
Thank you for reporting the issue.
I tried to reproduce the problem, however, I can not reproduce the issue.
And maven repo is online.
Could you please retry?
Also could you please confirm if you can access http://mobile.maven.couchbase.com/maven2/dev/com/couchbase/lite/couchbase-lite-android/2.0.0-DB021/couchbase-lite-android-2.0.0-DB021.aar ?
Thank you!

**Comment by jdulaney** [comment]
I've tried the past few days to no avail.

That link does not work. Instantly get:

This page isn’t working
mobile.maven.couchbase.com didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by hideki** [comment]
Hi @jdulaney,

It seems `mobile.maven.couchbase.com` is not accessible. 
Note: The host is accessible from the internal network.

Sorry for your inconvenience.

**Comment by hideki** [comment]
Hi @jdulaney,
Maven repo should be online now. Could you please try it again?
Thanks!

**Comment by jdulaney** [comment]
working now, thanks!
