### ISSUE TITLE
upgrade of 2.0 app doesn't show the docs from existing docs properly

### ISSUE THREAD

**Issue by hrajput89** [couchbaselabs/mobile-training-todo#171]
1. setup a cluster with todo 1.4 CBL app, SG 1.5 and CBS 5.0. 
`var retVal = new CoreAppStartHint {
                LoginEnabled = true,
                EncryptionEnabled = false,
                SyncEnabled = true,
                UsePrebuiltDB = false,
                ConflictResolution = false,
                Username = "todo"
            };`
2. create few list and task docs in CBL app and check if docs are getting synced.
3. deploy todo 2.0 app with following properties
`var retVal = new CoreAppStartHint {
                LoginEnabled = true,
                EncryptionEnabled = false,
                SyncEnabled = true,
                UsePrebuiltDB = true,
                Username = "todo"
            };`

**ISSUE**
1. Existing docs doesn't appear in app unless a new doc is created. 
2. Task list docs are not appearing properly.
https://www.dropbox.com/s/7yshyw98ujdnu5q/Screenshot%202018-01-11%2016.11.22.png?dl=0

**Comment by borrrden** [comment]
Please mention that this is .NET (and Xamarin iOS at that) or people so people will know before they start analyzing the code in your snippets.

Also provide logs from sync gateway and Couchbase Lite (You can call `Couchbase.Lite.Support.iOS.EnableTextLogging` to get logs to NSLog).

Is this upgrade related or will it happen if you use purely 2.0 only?
