### ISSUE TITLE
Attachment images added in ios do not show up in android

### ISSUE THREAD

**Issue by raghusarangapani** [couchbaselabs/mobile-training-todo#173]
### Steps
1. Compiled ToDo app.
2. Installed on a Nexus 6p device.
3. Create a list and a task.
4. Add attachment image for the list on ios
5. Check the same task on android

### Actual
Images attached in ios do not show up in android

**Comment by djpongh** [comment]
Filed under CBL Android https://github.com/couchbase/couchbase-lite-android/issues/1611

**Comment by tleyden** [comment]
The issue is that it's calling Blob.getContent() on a blob that's bigger than the limit of 8k.  The fix is to call the `getContentStream()` API instead.
