### ISSUE TITLE
The document deleted on the service can't sync to android client

### ISSUE THREAD

**Issue by loongsun** [couchbaselabs/mobile-training-todo#179]
@hideki 
hi,hideki
 I have tested this todo app on the db022 and sync_gateway 2.0.0(773),i found these issues.
```
1: when i create\update a document in the android app, the sync_gateway_error.log will post "409 Docment update conflict...(as user1).
2:when i delete a document on the service, the log will post " CRUD+:Doc user1.5cf99..... is not an SG write, base on cas. was:15184d1917b0000 syncs:"0x0000c933c84d1815"
3: i add  "enable_shared_bucket_access":true,
        "unsupported": {
        "enable_extended_attributes": true,
        "replicator_2":true
      }" to the sync_gateway.json,  when i delete a document on the service ,the log will post "WARNING: Sync fn exception:TypeError:Cannot access member 'type' of null; doc = map[_deleted:...,_rev:.... _id:....] -- db.(*Database).getChannelsAndAccess() at crud.go:1274
CRUD+:Did not update document "user1...." w/ xattr:500 Exception in JS sync function.
```

**Comment by hideki** [comment]
Hi @loongsun,
Thank you for trying to use our beta build.
From SG 2.0, the following block for SG config is not necessary. Please remove it from SG config.
```json
"unsupported": {
        "enable_extended_attributes": true,
        "replicator_2":true
      }"
```
Could you please share the updated test result with us?
Thanks!

**Comment by loongsun** [comment]
![772de10757a5aa37343060ad16e7997f](https://user-images.githubusercontent.com/13152718/37068922-1cc428d6-21ec-11e8-8538-b5eb2026050c.jpg)
![c6da3dff113a0d896030a0797198647b](https://user-images.githubusercontent.com/13152718/37068935-266c8a18-21ec-11e8-879a-ef66688afd3c.jpg)
![e16cf03828a0635ac3dabd4d303a526d](https://user-images.githubusercontent.com/13152718/37068938-27fa45aa-21ec-11e8-89c5-89e0852046b3.jpg)

**Comment by loongsun** [comment]
hi,hideki
if you test todo app as my order, you will find the same issue!

**Comment by hideki** [comment]
hi @loongsun,
I am not sure the clear steps to reproduce the issue.
Could you please provide detailed steps!
Hideki

**Comment by loongsun** [comment]
@hideki   use your todo app,  only update a docment or delete a docment.   you must see the sync_gateway_error.log  on  the service!

**Comment by loongsun** [comment]
hi ,hideki, i know the reasion of this issue,  your sync_gateway.json in the object  Out of date，can you import your sync_gateway.json in the android project!

**Comment by hideki** [comment]
@loongsun 
Try following config file with SG 2.0.0 latest beta build. Hope this helps you!
https://github.com/couchbaselabs/mobile-training-todo/blob/feature/2.0/android/sync-gateway-config.json
