### ISSUE TITLE
iOS: Layout of listview should account for nav bar in List Users view (iOS 8)

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-training-todo#18]
Using iOS 8, iPhone 5

Expected: The listview would start below nav bar
Actual: the listview is starts under the nav bar
![screenshot 2016-10-27 15 08 43](https://cloud.githubusercontent.com/assets/1365736/19787392/4b72ccee-9c57-11e6-80c2-02bf3fd3638e.png)

**Comment by pasin** [comment]
I couldn't reproduce this on my iPhone 6. Are there steps to reproduce this?

**Comment by sethrosetter** [comment]
@pasin Using iOS 8 iPhone 5, go to the Users view.
