### ISSUE TITLE
.NET: Logout failed on .NET

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-training-todo#26]
![screenshot 2016-10-31 15 21 16](https://cloud.githubusercontent.com/assets/1365736/19875106/50be45a6-9f87-11e6-962b-342b9b7e822f.png)

**Comment by borrrden** [comment]
Unable to reproduce this.  I can logout fine.  What is the start hint that you used?

**Comment by sethrosetter** [comment]
I haven't seen this since.
