### ISSUE TITLE
All: Moderator cannot delete list of other user

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-training-todo#31]
Steps to reproduce:

1. Create a list with user1
2. Moderator (not user1) should see list
3. Try to delete list as moderator, unable to do so

**Comment by jamiltz** [comment]
Fixed:
- [x] .NET
- [x] Android
- [x] iOS

**Comment by jamiltz** [comment]
Influenced by https://github.com/couchbaselabs/mobile-training-todo/issues/30

**Comment by jamiltz** [comment]
Verified for .NET and iOS. Needs fixing on Android.
