### ISSUE TITLE
All: Unsharing a list should remove list for the unshared users

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-training-todo#32]
Right now the behavior is to "freeze" the list. The user is unable to see updates to the list or any new changes. 

It would make more sense to detect unsharing similar to deletes and remove the list on the users that were unshared with.

**Comment by borrrden** [comment]
- [X] iOS
- [X] Android
- [X] .NET

**Comment by sethrosetter** [comment]
- Works on iOS sharing / unsharing with .NET
- Does not work when iOS shares / unshares with Android

**Comment by borrrden** [comment]
The only missing piece is Android reacting to the unsharing change and deleting the local document.

**Comment by jamiltz** [comment]
Android fix https://github.com/couchbaselabs/mobile-training-todo/pull/75. Closing and marking as testfest to verify it.
