### ISSUE TITLE
All: Add instruction wiki for test fest

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-training-todo#33]

**Comment by jamiltz** [comment]
@sethrosetter I update the main README and individual READMEs per platform in each folder ([ios for example](https://github.com/couchbaselabs/mobile-training-todo/tree/master/ios)).

I think this is enough to get anyone started in a test fest. The rest of the test fest instructions would be the Sync Gateway URL and who configures what features (forestdb, sqlite, encryption..). Feel free to close this issue if the current state has enough info.
