### ISSUE TITLE
Create IDE thumb drive

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-training-todo#65]
Only to assist with offline install

- [ ] Xcode 8 (Mac)
- [ ] Android Studio 2.2 (Mac / Windows)
- [ ] Android SDK 24
- [ ] Android Build Tools 24.0.3
- [ ] JDK 8 (Mac / Windows)
- [ ] Visual Studio 2015 Community Edition (Windows)

**Comment by djpongh** [comment]
Visual Studio 2015 Community Edition - we're OK as long as the following is true:
 Any number of your users may use the software to develop and test your applications released under Open Source Initiative (OSI) approved open source software licenses.

**Comment by hideki** [comment]
+ JDK 8 (for just in case)

**Comment by borrrden** [comment]
curl.exe for Windows
