### ISSUE TITLE
Content review

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/mobile-training-todo#68]
- [x] Different style for challenge
- [ ] Persist platform between page reloads

**Using the database**
- [x] Create a document - challenge: update the name field to your name and notice
- [x] Update a document - android only: should be doc.update instead of doc.putProperties. challenge: the challenge is to uppercase the text before it gets persisted. 
- [x] Delete a document - all: the concept of revisions will be covered in the next lesson. Provisional challenge: add a document listener to detect when the doc got deleted.
- [x] Query documents- Potential challenge: update map function to show something different on the UI.
- [ ] Data aggregation - all: show a screenshot of the UI for what the effect before explaining what grouping does. Outline around the rows that get emitted. Update aggregation data diagram with the same order as it was stored. Show key, value as title of column. Mention that the complete check is not done in the javascript function.
    ```
    }, new Reducer() {
        @Override
        public Object reduce(List<Object> keys, List<Object> values, boolean rereduce) {
            // keys: [0, 0]
            // values: [null, null]
            return values.size();
        }
    }, "1.0");
    ```
Add comment for `incompTasksCountLiveQuery.addChangeListener` snippet. Update the instructions to tell user to create tasks.

**Adding Sync**
- [ ] Install Sync gateway. point out that normally server is cbs, not wlarus. Check internal links.
- [ ] Adding sync. Add a diagram for local/remote.
- [ ] Automatic conflict resolution. Foosball and Table football. Add shake to create conflict on Android. 

**Adding Security**
- [ ] Explain what the config does. Delete the app to show it can't pull the same docs it pushed.
**Integration**

**Comment by djpongh** [comment]
Moved to Jira DOC-3019
