### ISSUE TITLE
Local path warning upon importing training project

### ISSUE THREAD

**Issue by raghusarangapani** [couchbaselabs/mobile-training-todo#76]
Steps:

1. Download the android project from the developer website:
http://developer.couchbase.com/documentation/mobile/1.3/training/develop/create-database/index.html
2. Unzip it
3. Launch Android studio and select "Open an existing Android Studio project" and select the android-project.

Actual:

A pop-up shows up that says 
"Sync Android SDKs
The path '/Users/jamesnocentini/Developer/adt-bundle/sdk' does not belong to a directory.

Android Studio will use this Android SDK instead '/Users/raghu.sarangapani/Library/Android/sdk' and will modify the project's local.properties file.

Attached is the screenshot

![screen shot 2016-12-07 at 2 11 19 pm 2](https://cloud.githubusercontent.com/assets/24398601/20989702/86f1de88-bc8a-11e6-907f-fcd64de828ee.png)

**Comment by jamiltz** [comment]
updated on the web page.
