### ISSUE TITLE
Android application rotates image 90 degrees

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-training-todo#99]
- Create an image on iOS, share with Android.
- The image shows up rotated 90 degrees.

**Comment by jamiltz** [comment]
Can't repro. Either it got fixed at some point but can't see when https://github.com/couchbaselabs/mobile-training-todo/commits/master/android/app/src/main/java/com/couchbase/todo/TasksFragment.java or it happens sometimes. Closing for now.

![mar-22-2017 13-01-55](https://cloud.githubusercontent.com/assets/2589337/24198936/c9144d9c-0eff-11e7-9894-c5aa495632c6.gif)
